language: java
cache:
  directories:
    - $HOME/.m2/
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - fakeroot
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
script:
  - mvn clean package
