version: "1.0.{build}"
image: Visual Studio 2017
build:
  verbosity: normal
build_script: mvn clean package
cache:
  - C:\Users\appveyor\.m2
artifacts:
  - path: 'target\**\*.exe'
    name: 'ShinyWrenchEXE'
